version: '2'
services:
    web1:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5000:5000"
        environment:
            PORT: 1151
        volumes:
            - ./web:/app
    web2:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5001:5000"
        environment:
            PORT: 1171
        volumes:
            - ./web:/app
    web3:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5002:5000"
        environment:
            PORT: 1181
        volumes:
            - ./web:/app
    nginx:
        image:
            nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    redis:
        image:
            redis
        volumes:
            - ./redis/redis.conf:/redis.conf
        command: redis-server /redis.conf
            
