version: '2'
services:
    web1:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5000:5000"
        environment:
            PORT: 1151
    web2:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5001:5000"
        environment:
            PORT: 1171
    web3:
        image: flask_web:latest
        #build: ./web
        ports:
            - "5002:5000"
        environment:
            PORT: 1181
    nginx:
        image:
            nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
