version: '2'
services:
    web:
        image: flask_web:latest
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            PORT: 1151
    redis:
        image:
            redis
