version: '2'
services:
    web:
        build: web/
        ports:
            - "5000"
        volumes:
            - ./web:/app
    nginx:
        build: nginx/
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    redis:
        image:
            redis
        volumes:
            - ./redis/redis.conf:/redis.conf
        command: redis-server /redis.conf
    consul:
        image:
            consul
        ports:
            - "8500:8500"
        command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0
